apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: helios-node-hpa
  namespace: helios
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: helios-node
  minReplicas: 1
  maxReplicas: 5  # Maximum 5 nodes based on available resources
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70  # Scale up when CPU > 70%
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80  # Scale up when memory > 80%
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60  # Wait 60s before scaling down
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 30  # Wait 30s before scaling up
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30 